### ISSUE TITLE
Errors in logs

### ISSUE THREAD

**Issue by MerdedSpade** [kyb3r/modmail#162]
2019-01-29T08:36:01.747091+00:00 app[worker.1]: Ignoring exception in on_command_error
2019-01-29T08:36:01.748600+00:00 app[worker.1]: Traceback (most recent call last):
2019-01-29T08:36:01.748661+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
2019-01-29T08:36:01.748663+00:00 app[worker.1]:     await coro(*args, **kwargs)
2019-01-29T08:36:01.748684+00:00 app[worker.1]:   File "bot.py", line 545, in on_command_error
2019-01-29T08:36:01.748685+00:00 app[worker.1]:     raise exception
2019-01-29T08:36:01.748710+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 898, in invoke
2019-01-29T08:36:01.748711+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
2019-01-29T08:36:01.748735+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 608, in invoke
2019-01-29T08:36:01.748736+00:00 app[worker.1]:     await self.prepare(ctx)
2019-01-29T08:36:01.748768+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 565, in prepare
2019-01-29T08:36:01.748770+00:00 app[worker.1]:     await self._verify_checks(ctx)
2019-01-29T08:36:01.748790+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 519, in _verify_checks
2019-01-29T08:36:01.748791+00:00 app[worker.1]:     raise CheckFailure('The check functions for command {0.qualified_name} failed.'.format(self))
2019-01-29T08:36:01.748828+00:00 app[worker.1]: discord.ext.commands.errors.CheckFailure: The check functions for command close failed.
2019-01-29T08:36:33.070312+00:00 app[worker.1]: Ignoring exception in on_message
2019-01-29T08:36:33.071662+00:00 app[worker.1]: Traceback (most recent call last):
2019-01-29T08:36:33.071728+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
2019-01-29T08:36:33.071730+00:00 app[worker.1]:     await coro(*args, **kwargs)
2019-01-29T08:36:33.071751+00:00 app[worker.1]:   File "bot.py", line 460, in on_message
2019-01-29T08:36:33.071752+00:00 app[worker.1]:     return await self.process_modmail(message)
2019-01-29T08:36:33.071786+00:00 app[worker.1]:   File "bot.py", line 406, in process_modmail
2019-01-29T08:36:33.071788+00:00 app[worker.1]:     thread = await self.threads.find_or_create(message.author)
2019-01-29T08:36:33.071793+00:00 app[worker.1]:   File "/app/core/thread.py", line 590, in find_or_create
2019-01-29T08:36:33.071794+00:00 app[worker.1]:     await self.create(recipient)
2019-01-29T08:36:33.071818+00:00 app[worker.1]:   File "/app/core/thread.py", line 581, in create
2019-01-29T08:36:33.071819+00:00 app[worker.1]:     channel.send(mention, embed=info_embed)
2019-01-29T08:36:33.071842+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/abc.py", line 772, in send
2019-01-29T08:36:33.071843+00:00 app[worker.1]:     data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
2019-01-29T08:36:33.071883+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/discord/http.py", line 214, in request
2019-01-29T08:36:33.071885+00:00 app[worker.1]:     raise HTTPException(r, data)
2019-01-29T08:36:33.071891+00:00 app[worker.1]: discord.errors.HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
2019-01-29T08:36:33.071892+00:00 app[worker.1]: In embed.author.url: Not a well formed URL.

**Comment by iamluca** [comment]
It looks like there is an issue with the `LOG_URL` in heroku. Please check your environment variables.

**Comment by AbovePlanet302** [comment]
Hey I just was testing my mod mail and when I sent a reply to my mods they tried to reply back but it just kept saying Mod Mail was typing

**Comment by Taaku18** [comment]
@AbovePlanet302 Hello, thanks for commenting. If you’re experiencing a problem with Modmail, please raise another issue on GitHub and post your Heroku logs. Alternatively, you can seek support in the Discord server.

**Comment by MerdedSpade** [comment]
Thank you!
