### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_linked_message_from_dm'

### ISSUE THREAD

**Issue by ARQAWA** [kyb3r/modmail#2752]
```
12/17/19 09:26:51 __main__[1110] - ERROR: Ignoring exception in on_message_delete.
12/17/19 09:26:51 __main__[1111] - ERROR: Unexpected exception:
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/fsl-modmail-xLTxmiAv/lib/python3.6/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 1081, in on_message_delete
    message = await thread.find_linked_message_from_dm(message)
AttributeError: 'NoneType' object has no attribute 'find_linked_message_from_dm'
12/17/19 09:29:21 __main__[1022] - WARNING: Failed to retrieve audit log: 'int' object has no attribute 'name'.
12/17/19 09:29:27 __main__[1110] - ERROR: Ignoring exception in on_message_delete.
12/17/19 09:29:27 __main__[1111] - ERROR: Unexpected exception:
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/fsl-modmail-xLTxmiAv/lib/python3.6/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 1081, in on_message_delete
    message = await thread.find_linked_message_from_dm(message)
AttributeError: 'NoneType' object has no attribute 'find_linked_message_from_dm'
12/17/19 09:29:43 __main__[1110] - ERROR: Ignoring exception in on_message_delete.
12/17/19 09:29:43 __main__[1111] - ERROR: Unexpected exception:
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/fsl-modmail-xLTxmiAv/lib/python3.6/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 1081, in on_message_delete
    message = await thread.find_linked_message_from_dm(message)
AttributeError: 'NoneType' object has no attribute 'find_linked_message_from_dm'
```

**Comment by StephenDaDev** [comment]
Bug. Do not close.
