### ISSUE TITLE
Bot is unable to make new threads into mod mail threads

### ISSUE THREAD

**Issue by Cuyoya** [kyb3r/modmail#2819]
**Describe the bug**
New mod mail threads aren't being created properly- the thread is made, but nothing is posted and the thread is empty and not counted as a Mod Mail Thread.
DMs to the bot shows any message is being shown as not sent with the crossed out circle emoji.

**Bot Info**
Bot version: 3.4.1
Host method: Heroku

**To Reproduce**
-Try to send literally any mod mail message

**Error Logs**
Bot Debug: https://hasteb.in/cihedezu
Heroku Logs: https://pastebin.com/embed_js/nAaKqytS

**Screenshots**
https://imgur.com/a/d6no63T

**Comment by Inzanit** [comment]
Same issue for me:

```
2020-07-09 06:14:48 __main__[102] - INFO: -------------------------
2020-07-09 06:14:48 __main__[103] - INFO: ┌┬┐┌─┐┌┬┐┌┬┐┌─┐┬┬
2020-07-09 06:14:48 __main__[104] - INFO: ││││ │ │││││├─┤││
2020-07-09 06:14:48 __main__[105] - INFO: ┴ ┴└─┘─┴┘┴ ┴┴ ┴┴┴─┘
2020-07-09 06:14:48 __main__[106] - INFO: v3.4.1
2020-07-09 06:14:48 __main__[107] - INFO: Authors: kyb3r, fourjr, Taaku18
2020-07-09 06:14:48 __main__[108] - INFO: -------------------------
2020-07-09 06:14:53 cogs.utility[603] - INFO: -------------------------
2020-07-09 06:14:53 cogs.utility[612] - INFO: Activity set to: Watching for DMs.
2020-07-09 06:14:53 cogs.utility[619] - INFO: No status has been set.
2020-07-09 06:14:53 __main__[414] - INFO: -------------------------
2020-07-09 06:14:53 __main__[416] - INFO: Logged in as: XXX
2020-07-09 06:14:53 __main__[417] - INFO: Bot ID: XXX
2020-07-09 06:14:53 __main__[421] - INFO: Owners: XXX
2020-07-09 06:14:53 __main__[422] - INFO: Prefix: ?
2020-07-09 06:14:53 __main__[423] - INFO: Guild Name: C#
2020-07-09 06:14:53 __main__[424] - INFO: Guild ID: 143867839282020352
2020-07-09 06:14:53 __main__[427] - INFO: -------------------------
2020-07-09 06:14:53 __main__[433] - INFO: There are 0 thread(s) pending to be closed.
2020-07-09 06:14:53 __main__[434] - INFO: -------------------------
2020-07-09 06:16:27 cogs.modmail[1182] - INFO: Attempting to fix a broken thread inzanit-0101.
2020-07-09 06:16:27 cogs.modmail[1224] - WARNING: No genesis message found.
2020-07-09 06:16:35 __main__[1022] - WARNING: Failed to retrieve audit log: 'int' object has no attribute 'name'.
2020-07-09 06:16:42 __main__[1165] - ERROR: Unexpected exception:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/cogs/modmail.py", line 913, in contact
    await thread.channel.send(embed=embed)
AttributeError: 'NoneType' object has no attribute 'send'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'send'
2020-07-09 06:18:14 __main__[1022] - WARNING: Failed to retrieve audit log: 'int' object has no attribute 'name'.
2020-07-09 06:18:25 core.thread[918] - WARNING: Found existing thread for 104975006542372864 but the channel is invalid.
2020-07-09 06:18:28 core.thread[977] - WARNING: Found an existing thread for Inzanit#0101, closing previous thread.
2020-07-09 06:18:31 __main__[765] - ERROR: Failed to send message:
Traceback (most recent call last):
  File "bot.py", line 763, in process_dm_modmail
    await thread.send(message)
  File "/app/core/thread.py", line 707, in send
    self.bot.loop.create_task(self.bot.api.append_log(message, channel_id=self.channel.id))
AttributeError: 'NoneType' object has no attribute 'id'
2020-07-09 06:18:31 __main__[765] - ERROR: Failed to send message:
Traceback (most recent call last):
  File "bot.py", line 763, in process_dm_modmail
    await thread.send(message)
  File "/app/core/thread.py", line 707, in send
    self.bot.loop.create_task(self.bot.api.append_log(message, channel_id=self.channel.id))
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by charliea21** [comment]
I can replicate this issue on both my 2 instances of modmail (they run on separate servers). However I'm self hosting (not using Heroku).

It appears to create 2 channels when someone sends a message.

Logs:

```
Loading .env environment variables…
07/09/20 03:34:45 __main__[128] - INFO: -------------------------
07/09/20 03:34:45 __main__[136] - INFO: Logging level: INFO
07/09/20 03:34:45 __main__[138] - INFO: Log file: /root/rmodmail/temp/logfile.log
07/09/20 03:34:45 __main__[102] - INFO: -------------------------
07/09/20 03:34:45 __main__[103] - INFO: ┌┬┐┌─┐┌┬┐┌┬┐┌─┐┬┬
07/09/20 03:34:45 __main__[104] - INFO: ││││ │ │││││├─┤││
07/09/20 03:34:45 __main__[105] - INFO: ┴ ┴└─┘─┴┘┴ ┴┴ ┴┴┴─┘
07/09/20 03:34:45 __main__[106] - INFO: v3.4.1
07/09/20 03:34:45 __main__[107] - INFO: Authors: kyb3r, fourjr, Taaku18
07/09/20 03:34:45 __main__[108] - INFO: -------------------------
07/09/20 03:34:50 cogs.utility[603] - INFO: -------------------------
07/09/20 03:34:50 cogs.utility[612] - INFO: Activity set to: Playing DM for support.
07/09/20 03:34:50 cogs.utility[619] - INFO: No status has been set.
07/09/20 03:34:50 __main__[414] - INFO: -------------------------
07/09/20 03:34:50 __main__[416] - INFO: Logged in as: name#0000
07/09/20 03:34:50 __main__[417] - INFO: Bot ID: 1234
07/09/20 03:34:50 __main__[421] - INFO: Owners: Owners Here
07/09/20 03:34:50 __main__[422] - INFO: Prefix: .
07/09/20 03:34:50 __main__[423] - INFO: Guild Name: Name Here
07/09/20 03:34:50 __main__[424] - INFO: Guild ID: 1234
07/09/20 03:34:50 __main__[427] - INFO: -------------------------
07/09/20 03:34:50 __main__[433] - INFO: There are 1 thread(s) pending to be closed.
07/09/20 03:34:50 __main__[434] - INFO: -------------------------
Task exception was never retrieved
future: <Task finished coro=<Thread.setup() done, defined at /root/modmail/core/thread.py:79> exception=TypeError("__new__() got an unexpected keyword argument 'allow_new'")>
Traceback (most recent call last):
  File "/root/modmail/core/thread.py", line 99, in setup
    reason="Creating a thread channel.",
  File "/root/.local/share/virtualenvs/modmail-pMPq0_I8/lib/python3.7/site-packages/discord/guild.py", line 883, in create_text_channel
    channel = TextChannel(state=self._state, guild=self, data=data)
  File "/root/.local/share/virtualenvs/modmail-pMPq0_I8/lib/python3.7/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)
  File "/root/.local/share/virtualenvs/modmail-pMPq0_I8/lib/python3.7/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "/root/.local/share/virtualenvs/modmail-pMPq0_I8/lib/python3.7/site-packages/discord/abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'allow_new'
07/09/20 03:34:58 __main__[765] - ERROR: Failed to send message:
Traceback (most recent call last):
  File "bot.py", line 763, in process_dm_modmail
    await thread.send(message)
  File "/root/modmail/core/thread.py", line 707, in send
    self.bot.loop.create_task(self.bot.api.append_log(message, channel_id=self.channel.id))
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by linuswillner** [comment]
Seems to be related to https://github.com/Rapptz/discord.py/issues/5109

**Comment by Inzanit** [comment]
Looks like this was fixed with a bump of the Discord py version

**Comment by DAzVise** [comment]
This has been fixed in the latest modmail version, please update your bot (and if you're hosting locally install the requirements again with `pipenv install`)

**Comment by Cuyoya** [comment]
> This has been fixed in the latest modmail version, please update your bot (and if you're hosting locally install the requirements again with `pipenv install`)

...I'm running the latest version, though?

**Comment by lorenzo132** [comment]
What version are you using? @Cuyoya

**Comment by Cuyoya** [comment]
It's literally in the OP, but v3.4.1

**Comment by lorenzo132** [comment]
Hey, We released a update a couple hours ago with the fix to the bug u are facing.  Follow the following guide on how to update https://github.com/kyb3r/modmail/wiki/updating

**Comment by Cuyoya** [comment]
Updated and that seems to have fixed it, yup. Thanks!

**Comment by Cuyoya** [comment]
Updated and that seems to have fixed it, yup. Thanks!
