### ISSUE TITLE
Bulk Permissions override [Command request]

### ISSUE THREAD

**Issue by ririko5834** [kyb3r/modmail#2900]
**Is your feature request related to a problem? Please describe.**
I want to bulk override permissions for command category
Now i need to do this manually for every commands and it is hard.

**Describe the solution you'd like**
Add command `?perms buld_override (command category/all commands) (perms level)`
It should override all commands in provided category

**Describe alternatives you've considered**
Maybe you can send me code how to do this using ?eval command.

**Who will this benefit**
Users who want to override permissions in more commands.

**Comment by fourjr** [comment]
Possible solution: Support command groups in `?perms add/remove/override`.

For now, here's an eval that can help you:
```python
?eval group_name = 'put name within these quotes, e.g. perms'
level_name = 'put group name here'

group = bot.get_command(group_name.lower())
for i in set(group.walk_commands()):
    await ctx.invoke(bot.get_command('perms add'), command_name=i.qualified_name.lower(), level_name=level_name)
```

**Comment by ririko5834** [comment]
OK, can you create also command for it in new release?

**Comment by ririko5834** [comment]
@fourjr Hello, i am getting error:
```SyntaxError: unexpected EOF while parsing (<string>, line 7)```

I did the following:
```
?eval group_name = 'modmail'
level_name = 'OWNER'

group = bot.get_command(group_name.lower())
for i in set(group.walk_commands()):
    await ctx.invoke(bot.get_command('perms override'), command_name=i.qualified_name.lower(), level_name=level_name
```

**Comment by fourjr** [comment]
You missed out a bracket at the end.

**Comment by ririko5834** [comment]
@fourjr Now this
```
Traceback (most recent call last):
  File "/home/modmail/cogs/utility.py", line 2015, in eval_
    ret = await func()
  File "<string>", line 6, in func
AttributeError: 'NoneType' object has no attribute 'walk_commands'
```

**Comment by fourjr** [comment]
`modmail` is not a valid group name, could we discuss this in discord?

**Comment by ririko5834** [comment]
![image](https://user-images.githubusercontent.com/64729293/99958647-0bb3c680-2d8a-11eb-81cb-e81bae4cb24f.png) I think that it is Modmail because its in help menu
What are group names?

**Comment by fourjr** [comment]
Let's discuss this on the [discord server[(https://discord.gg/etJNHCQ)

**Comment by lorenzo132** [comment]
Hi, this has been added in https://github.com/modmail-dev/Modmail/pull/3417

I'll be closing this issue.
