### ISSUE TITLE
[BUG] Unable to install plugin

### ISSUE THREAD

**Issue by Mohammad626** [kyb3r/modmail#2921]
Alright so this message keeps popping up when I use a plugin add command and this keeps coming up “Failed to download plugin, check logs for error. 
<class ‘cogs.plugins.InvalidPluginError’>: Plugin not found”. I’m trying to figure out what’s going on but it’s useless.

**Bot Info**
Bot version (check with `@modmail about`): 3.7.13
Host method (Heroku, self-host, etc): Heroku

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? Owners.
2. Where can it be reproduced (ex. in thread channels, recipient DM's)? It’s a plugin command so, in any channel I guess?
3. Done what to cause the error? All I know is that when I run a command like for example “?plugins add fun” this message would pop up “ Failed to download plugin, check logs for error. 
<class ‘cogs.plugins.InvalidPluginError’>: Plugin not found”
4. Any recently made changes to your bot? Not any major ones.

**Error Logs**
If your Modmail bot is online, type `@modmail debug hastebin` and include the link here.
If your Modmail bot is not online or the previous command did not generate a link, do the following:

1. Select your *bot* application at https://dashboard.heroku.com
2. [Restart your bot](https://i.imgur.com/3FcrlKz.png)
3. Reproduce the error to populate the error logs
4. [Copy and paste the logs](https://i.imgur.com/TTrhitm.png)

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**
Logs: 2020-12-25T06:40:31.823381+00:00 app[worker.1]: 12/25/20 06:40:31 __main__[475] - INFO: -------------------------
2020-12-25T06:40:31.823998+00:00 app[worker.1]: 12/25/20 06:40:31 __main__[481] - INFO: There are 0 thread(s) pending to be closed.
2020-12-25T06:40:31.824526+00:00 app[worker.1]: 12/25/20 06:40:31 __main__[482] - INFO: -------------------------
2020-12-25T06:40:32.856340+00:00 app[worker.1]: 12/25/20 06:40:32 cogs.plugins[347] - WARNING: Unable to download plugin TheKinG2149/modmail-plugins/fun@master.
2020-12-25T06:40:32.856350+00:00 app[worker.1]: Traceback (most recent call last):
2020-12-25T06:40:32.856350+00:00 app[worker.1]:   File "/app/cogs/plugins.py", line 345, in plugins_add
2020-12-25T06:40:32.856351+00:00 app[worker.1]:     await self.download_plugin(plugin, force=True)
2020-12-25T06:40:32.856351+00:00 app[worker.1]:   File "/app/cogs/plugins.py", line 179, in download_plugin
2020-12-25T06:40:32.856352+00:00 app[worker.1]:     raise InvalidPluginError("Plugin not found")
2020-12-25T06:40:32.856352+00:00 app[worker.1]: cogs.plugins.InvalidPluginError: Plugin not found

**Comment by fourjr** [comment]
Cannot be reproduced on latest version.

**Comment by Mohammad626** [comment]
> Cannot be reproduced on latest version.

So the solution is, I have to be on a different version?

**Comment by fourjr** [comment]
Try again in the latest version after it is released. For now, I will close this issue. Plugin errors should be reported within the discord server.
