### ISSUE TITLE
Failed to load paths: The system cannot find the path specified.

### ISSUE THREAD

**Issue by OperatorEK0** [kyb3r/modmail#2940]
I was asked by an Admin on Discord to post my issue on here. I am trying to self-host Modmail on a Windows Server 2019 machine but each time I run the `pipenv install` command I get the follow error message:

- My Python version is 3.7.9 with access to PATH and in C:\ drive.
- I ran the command in a command prompt with administrator privileges.

```C:\Users\Administrator\Desktop\Modmail>pipenv install
Creating a virtualenv for this project...
Pipfile: C:\Users\Administrator\Desktop\Modmail\Pipfile
Using C:/Python37/python.exe (3.7.9) to create virtualenv...
[====] Creating virtual environment...created virtual environment CPython3.7.9.final.0-64 in 7820ms
  creator CPython3Windows(dest=C:\Users\Administrator\.virtualenvs\Modmail-zMg-DQ-A, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\Administrator\AppData\Local\pypa\virtualenv)
    added seed packages: pip==20.3.3, setuptools==51.0.0, wheel==0.36.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Successfully created virtual environment!
Failed to load paths: The system cannot find the path specified.

Output:
Virtualenv location: C:\Users\Administrator\.virtualenvs\Modmail-zMg-DQ-A
Installing dependencies from Pipfile.lock (6644b7)...
Failed to load paths: The system cannot find the path specified.

Output:
Failed to load paths: The system cannot find the path specified.

Output:
An error occurred while installing aiohttp==3.6.3 --hash=sha256:687461cd974722110d1763b45c5db4d2cdee8d50f57b00c43c7590d1dd77fc5c --hash=sha256:60f4caa3b7f7a477f66ccdd158e06901e1d235d572283906276e3803f6b098f5 --hash=sha256:698cd7bc3c7d1b82bb728bae835724a486a8c376647aec336aa21a60113c3645 --hash=sha256:66d64486172b032db19ea8522328b19cfb78a3e1e5b62ab6a0567f93f073dea0 --hash=sha256:1a4160579ffbc1b69e88cb6ca8bb0fbd4947dfcbf9fb1e2a4fc4c7a4a986c1fe --hash=sha256:206c0ccfcea46e1bddc91162449c20c72f308aebdcef4977420ef329c8fcc599 --hash=sha256:c506853ba52e516b264b106321c424d03f3ddef2813246432fa9d1cefd361c81 --hash=sha256:fb83326d8295e8840e4ba774edf346e87eca78ba8a89c55d2690352842c15ba5 --hash=sha256:470e4c90da36b601676fe50c49a60d34eb8c6593780930b1aa4eea6f508dfa37 --hash=sha256:2ad493de47a8f926386fa6d256832de3095ba285f325db917c7deae0b54a9fc8 --hash=sha256:797456399ffeef73172945708810f3277f794965eb6ec9bd3a0c007c0476be98 --hash=sha256:a885432d3cabc1287bcf88ea94e1826d3aec57fd5da4a586afae4591b061d40d --hash=sha256:319b490a5e2beaf06891f6711856ea10591cfe84fe9f3e71a721aa8f20a0872a! Will try again.
An error occurred while installing appdirs==1.4.4 --hash=sha256:a841dacd6b99318a741b166adb07e19ee71a274450e68237b4650ca1055ab128 --hash=sha256:7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41! Will try again.
An error occurred while installing async-timeout==3.0.1; python_full_version >= '3.5.3' --hash=sha256:4291ca197d287d274d0b6cb5d6f8f8f82d434ed288f962539ff18cc9012f9ea3 --hash=sha256:0c3c816a028d47f659d6ff5c745cb2acf1f966da1fe5c19c77a70282b25f4c5f! Will try again.
An error occurred while installing attrs==20.3.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3' --hash=sha256:31b2eced602aa8423c2aea9c76a724617ed67cf9513173fd3a4f03e3a929c7e6 --hash=sha256:832aa3cde19744e49938b91fea06d69ecb9e649c93ba974535d08ad92164f700! Will try again.
An error occurred while installing certifi==2020.12.5 --hash=sha256:719a74fb9e33b9bd44cc7f3a8d94bc35e4049deebe19ba7d8e108280cfd59830 --hash=sha256:1a4995114262bffbc2413b159f2a1a480c969de6e6eb13ee966d470af86af59c! Will try again.
An error occurred while installing chardet==3.0.4 --hash=sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691 --hash=sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae! Will try again.
An error occurred while installing colorama==0.4.4 --hash=sha256:9f47eda37229f68eee03b24b9748937c7dc3868f906e8ba69fbcbdd3bc5dc3e2 --hash=sha256:5941b2b48a20143d2267e95b1c2a7603ce057ee39fd88e7329b0c292aa16869b! Will try again.
An error occurred while installing discord.py==1.6.0 --hash=sha256:ba8be99ff1b8c616f7b6dcb700460d0222b29d4c11048e74366954c465fdd05f --hash=sha256:3df148daf6fbcc7ab5b11042368a3cd5f7b730b62f09fb5d3cbceff59bcfbb12! Will try again.
An error occurred while installing distlib==0.3.1 --hash=sha256:edf6116872c863e1aa9d5bb7cb5e05a022c519a4594dc703843343a9ddd9bff1 --hash=sha256:8c09de2c67b3e7deef7184574fc060ab8a793e7adbb183d942c389c8b13c52fb! Will try again.
An error occurred while installing dnspython==1.16.0 --hash=sha256:f69c21288a962f4da86e56c4905b49d11aba7938d3d740e80d9e366ee4f1632d --hash=sha256:36c5e8e38d4369a08b6780b7f27d790a292b2b08eea01607865bf0936c558e01! Will try again.
An error occurred while installing emoji==0.6.0 --hash=sha256:e42da4f8d648f8ef10691bc246f682a1ec6b18373abfd9be10ec0b398823bd11! Will try again.
An error occurred while installing filelock==3.0.12 --hash=sha256:929b7d63ec5b7d6b71b0fa5ac14e030b3f70b75747cef1b10da9b879fef15836 --hash=sha256:18d82244ee114f543149c66a6e0c14e9c4f8a1044b5cdaadd0f82159d6a6ff59! Will try again.
An error occurred while installing idna==3.1; python_version >= '3.4' --hash=sha256:5205d03e7bcbb919cc9c19885f9920d622ca52448306f2377daede5cf3faac16 --hash=sha256:c5b02147e01ea9920e6b0a3f1f7bb833612d507592c837a6c49552768f4054e1! Will try again.
An error occurred while installing isodate==0.6.0 --hash=sha256:2e364a3d5759479cdb2d37cce6b9376ea504db2ff90252a2e5b7cc89cc9ff2d8 --hash=sha256:aa4d33c06640f5352aca96e4b81afd8ab3b47337cc12089822d6f322ac772c81! Will try again.
An error occurred while installing motor==2.3.0 --hash=sha256:f1692b760d834707e3477996ce8d407af8cd61c1a2abedbf81c22ef14675e61a --hash=sha256:428d94750123d19fcd0a89b8671ff9b4656f205217bad9f44161748c64c5fc80! Will try again.
An error occurred while installing multidict==4.7.6; python_version >= '3.5' --hash=sha256:fcfbb44c59af3f8ea984de67ec7c306f618a3ec771c2843804069917a8f2e255 --hash=sha256:feed85993dbdb1dbc29102f50bca65bdc68f2c0c8d352468c25b54874f23c39d --hash=sha256:1ece5a3369835c20ed57adadc663400b5525904e53bae59ec854a5d36b39b21a --hash=sha256:4538273208e7294b2659b1602490f4ed3ab1c8cf9dbdd817e0e9db8e64be2507 --hash=sha256:fbb77a75e529021e7c4a8d4e823d88ef4d23674a202be4f5addffc72cbb91430 --hash=sha256:5cf311a0f5ef80fe73e4f4c0f0998ec08f954a6ec72b746f3c179e37de1d210d --hash=sha256:f07acae137b71af3bb548bd8da720956a3bc9f9a0b87733e0899226a2317aeb7 --hash=sha256:d14842362ed4cf63751648e7672f7174c9818459d169231d03c56e84daf90b7c --hash=sha256:275ca32383bc5d1894b6975bb4ca6a7ff16ab76fa622967625baeebcf8079000 --hash=sha256:9456e90649005ad40558f4cf51dbb842e32807df75146c6d940b6f5abb4a78f3 --hash=sha256:c026fe9a05130e44157b98fea3ab12969e5b60691a276150db9eda71710cd10b --hash=sha256:5141c13374e6b25fe6bf092052ab55c0c03d21bd66c94a0e3ae371d3e4d865a5 --hash=sha256:e0d072ae0f2a179c375f67e3da300b47e1a83293c554450b29c900e50afaae87 --hash=sha256:6513728873f4326999429a8b00fc7ceddb2509b01d5fd3f3be7881a257b8d463 --hash=sha256:7388d2ef3c55a8ba80da62ecfafa06a1c097c18032a501ffd4cabbc52d7f2b19 --hash=sha256:3750f2205b800aac4bb03b5ae48025a64e474d2c6cc79547988ba1d4122a09e2 --hash=sha256:51a4d210404ac61d32dada00a50ea7ba412e6ea945bbe992e4d7a595276d2ec7! Will try again.
An error occurred while installing natural==0.2.0 --hash=sha256:18c83662d2d33fd7e6eee4e3b0d7366e1ce86225664e3127a2aaf0a3233f7df2! Will try again.
An error occurred while installing parsedatetime==2.6 --hash=sha256:cb96edd7016872f58479e35879294258c71437195760746faffedb692aef000b --hash=sha256:4cb368fbb18a0b7231f4d76119165451c8d2e35951455dfee97c62a87b04d455! Will try again.
An error occurred while installing pipenv==2020.11.15 --hash=sha256:4ab2f60742184d851ac44b9e1d423afe71dc2ea7a68bde07eb890c8b4ce5a420 --hash=sha256:8253fe6f9cfb3791a54da8a0571f73c918cb3457dd908684c1800a13a06ec4c1! Will try again.
An error occurred while installing pymongo==3.11.2 --hash=sha256:0a53a751d977ad02f1bd22ddb6288bb4816c4758f44a50225462aeeae9cbf6a0 --hash=sha256:d6f82e86896a8db70e8ae8fa4b7556a0f188f1d8a6c53b2ba229889d55a59308 --hash=sha256:4942a5659ae927bb764a123a6409870ca5dd572d83b3bfb71412c9a191bbf792 --hash=sha256:c046e09e886f4539f8626afba17fa8f2e6552731f9384e2827154e3e3b7fda4e --hash=sha256:82d5ded5834b6c92380847860eb28dcaf20b847a27cee5811c4aaceef87fd280 --hash=sha256:a118a1df7280ffab7fe0f3eab325868339ff1c4d5b8e0750db0f0a796da8f849 --hash=sha256:c812b6e53344e92f10f12235219fb769c491a4a87a02c9c3f93fe632e493bda8 --hash=sha256:3646c2286d889618d43e01d9810ac1fc17709d2b4dec61366df5edc8ba228b3e --hash=sha256:7f0c507e1f108790840d6c4b594019ebf595025c324c9f7e9c9b2b15b41f884e --hash=sha256:fc4946acb6cdada08f60aca103b61334995523da65be5fe816ea8571c9967d46 --hash=sha256:6122470dfa61d4909b75c98012c1577404ba4ab860d0095e0c6980560cb3711f --hash=sha256:1222025db539641071a1b67f6950f65a6342a39db5b454bf306abd6954f1ad8a --hash=sha256:9d19843568df9d263dc92ae4cc2279879add8a26996473f9155590cac635b321 --hash=sha256:76579fcf77052b39796fe4a11818d1289dd48cffe15951b3403288fa163c29f6 --hash=sha256:9be785bd4e1ba0148fb00ca84e4dbfbd1c74df3af3a648559adc60b0782f34de --hash=sha256:c6cf288c9e03195d8e12b72a6388b32f18a5e9c2545622417a963e428e1fe496 --hash=sha256:264843ce2af0640994a4331148ef5312989bc004678c457460758766c9b4decc --hash=sha256:5980509801cbd2942df31714d055d89863684b4de26829c349362e610a48694e --hash=sha256:5ad7b96c27acd7e256b33f47cf3d23bd7dd902f9c033ae43f32ffcbc37bebafd --hash=sha256:c1d1992bbdf363b22b5a9543ab7d7c6f27a1498826d50d91319b803ddcf1142e --hash=sha256:944ed467feb949e103555863fa934fb84216a096b0004ca364d3ddf9d18e2b9e --hash=sha256:6700e251c6396cc05d7460dc05ef8e19e60a7b53b62c007725b48e123aaa2b1c --hash=sha256:46792b71ab802d9caf1fc9d52e83399ef8e1a36e91eef4d827c06e36b8df2230 --hash=sha256:ed98683d8f01f1c46ef2d02469e04e9a8fe9a73a9741a4e6e66677a73b59bec8 --hash=sha256:b875bb4b438931dce550e170bfb558597189b8d0160f4ac60f14a21955161699 --hash=sha256:82f6e42ba40440a7e0a20bfe12465a3b62d65966a4c7ad1a21b36ffff88de6fe --hash=sha256:270a1f6a331eac3a393090af06df68297cb31a8b2df0bdcbd97dc613c5758e78 --hash=sha256:ce9964c117cbe5cf6269f30a2b334d28675956e988b7dbd0b4f7370924afda2e --hash=sha256:cc421babc687dc52ce0fc19787b2404518ca749d9db59576100946ff886f38ed --hash=sha256:082832a59da18efab4d9148cca396451bac99da9757f31767f706e828b5b8500 --hash=sha256:019ddf7ced8e42cc6c8c608927c799be8097237596c94ffe551f6ef70e55237e --hash=sha256:422069f2cebf58c9dd9e8040b4768f7be4f228c95bc4505e8fa8e7b4f7191ad8 --hash=sha256:b4294ddf76452459433ecfa6a93258608b5e462c76ef15e4695ed5e2762f009f --hash=sha256:8d669c720891781e7c82d412cad39f9730ef277e3957b48a3344dae47d3caa03 --hash=sha256:44376a657717de8847d5d71a9305f3595c7e78c91ac77edbb87058d12ede87a6 --hash=sha256:b50af6701b4a5288b77fb4db44a363aa9485caf2c3e7a40c0373fd45e34440af --hash=sha256:21d7b48567a1c80f9266e0ab61c1218a31279d911da345679188733e354f81cc --hash=sha256:540dafd6f4a0590fc966465c726b80fa7c0804490c39786ef29236fe68c94401 --hash=sha256:7e69fa025a1db189443428f345fea5555d16413df6addc056e17bb8c9794b006 --hash=sha256:b95d2c2829b5956bf54d9a22ffec911dea75abf0f0f7e0a8a57423434bfbde91 --hash=sha256:ce53c00be204ec4428d3c1f3c478ae89d388efec575544c27f57b61e9fa4a7f2 --hash=sha256:45728e6aae3023afb5b2829586d1d2bfd9f0d71cfd7d3c924b71a5e9aef617a8 --hash=sha256:4be4fe9d18523da98deeb0b554ac76e1dc1562ee879d62572b34dda8593efcc1 --hash=sha256:d9d3ae537f61011191b2fd6f8527b9f9f8a848b37d4c85a0f7bb28004c42b546 --hash=sha256:202ea1d4edc8a5439fc179802d807b49e7e563207fea5610779e56674ac770c6 --hash=sha256:061d59f525831c4051af0b6dbafa62b0b8b168d4ef5b6e3c46d0811b8499d100 --hash=sha256:6aac7e0e8de92f11a410eb68c24a2decbac6f094e82fd95d22546d0168e7a18b --hash=sha256:6e7a6057481a644970e43475292e1c0af095ca39a20fe83781196bd6e6690a38 --hash=sha256:813db97e9955b6b1b50b5cebd18cb148580603bb9b067ea4c5cc656b333bc906 --hash=sha256:96c6aef7ffb0d37206c0342abb82d874fa8cdc344267277ec63f562b94335c22 --hash=sha256:ef18aa15b1aa18c42933deed5233b3284186e9ed85c25d2704ceff5099a3964c --hash=sha256:3ec8f8e106a1476659d8c020228b45614daabdbdb6c6454a843a1d4f77d13339 --hash=sha256:c2b67881392a9e85aa108e75f62cdbe372d5a3f17ea5f8d3436dcf4662052f14 --hash=sha256:1580fad512c678b720784e5c9018621b1b3bd37fb5b1633e874738862d6435c7 --hash=sha256:fa741e9c805567239f845c7e9a016aff797f9bb02ff9bc8ccd2fbd9eafefedd4 --hash=sha256:29a6840c2ac778010547cad5870f3db2e080ad7fad01197b07fff993c08692c8 --hash=sha256:e565d1e4388765c135052717f15f9e0314f9d172062444c6b3fc0002e93ed04b --hash=sha256:047cc2007b280672ddfdf2e7b862aad8d898f481f65bbc9067bfa4e420a019a9 --hash=sha256:646d4d30c5aa7c0ddbfe9b990f0f77a88621024a21ad0b792bd9d58caa9611f0 --hash=sha256:6175fd105da74a09adb38f93be96e1f64873294c906e5e722cbbc5bd10c44e3b --hash=sha256:047c325c4a96e7be7d11acf58639bcf71a81ca212d9c6590e3369bc28678647a --hash=sha256:523804bd8fcb5255508052b50073a27c701b90a73ea46e29be46dad5fe01bde6 --hash=sha256:36b9b98a39565a8f33803c81569442b35e749a72fb1aa7d0bcdb1a33052f8bcc --hash=sha256:fcc66d17a3363b7bd6d2655de8706e25a3cd1be2bd1b8e8d8a5c504a6ef893ae! Will try again.
An error occurred while installing python-dateutil==2.8.1 --hash=sha256:75bb3f31ea686f1197762692a9ee6a7550b59fc6ca3a1f4b5d7e32fb98e2da2a --hash=sha256:73ebfe9dbf22e832286dafa60473e4cd239f8592f699aa5adaf10050e6e1823c! Will try again.
An error occurred while installing python-dotenv==0.15.0 --hash=sha256:0c8d1b80d1a1e91717ea7d526178e3882732420b03f08afea0406db6402e220e --hash=sha256:587825ed60b1711daea4832cf37524dfd404325b7db5e25ebe88c495c9f807a0! Will try again.
An error occurred while installing six==1.15.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2' --hash=sha256:8b74bedcbbbaca38ff6d7491d76f2b06b3592611af620f8426e82dddb04a5ced --hash=sha256:30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259! Will try again.
An error occurred while installing uvloop==0.14.0; sys_platform != 'win32' --hash=sha256:4315d2ec3ca393dd5bc0b0089d23101276778c304d42faff5dc4579cb6caef09 --hash=sha256:b4f591aa4b3fa7f32fb51e2ee9fea1b495eb75b0b3c8d0ca52514ad675ae63f7 --hash=sha256:bcac356d62edd330080aed082e78d4b580ff260a677508718f88016333e2c9c5 --hash=sha256:afd5513c0ae414ec71d24f6f123614a80f3d27ca655a4fcf6cabe50994cc1891 --hash=sha256:f07909cd9fc08c52d294b1570bba92186181ca01fe3dc9ffba68955273dd7362 --hash=sha256:08b109f0213af392150e2fe6f81d33261bb5ce968a288eb698aad4f46eb711bd --hash=sha256:e7514d7a48c063226b7d06617cbb12a14278d4323a065a8d46a7962686ce2e95 --hash=sha256:123ac9c0c7dd71464f58f1b4ee0bbd81285d96cdda8bc3519281b8973e3a461e --hash=sha256:4544dcf77d74f3a84f03dd6278174575c44c67d7165d4c42c71db3fdc3860726! Will try again.
  ================================ 27/27 - 00:00:10
An error occurred while installing virtualenv==20.2.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3' --hash=sha256:b7a8ec323ee02fb2312f098b6b4c9de99559b462775bc8fe3627a73706603c1b --hash=sha256:54b05fc737ea9c9ee9f8340f579e5da5b09fb64fd010ab5757eb90268616907c! Will try again.
An error occurred while installing virtualenv-clone==0.5.4; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3' --hash=sha256:07e74418b7cc64f4fda987bf5bc71ebd59af27a7bc9e8a8ee9fd54b1f2390a27 --hash=sha256:665e48dd54c84b98b71a657acb49104c54e7652bce9c1c4f6c6976ed4c827a29! Will try again.
An error occurred while installing yarl==1.5.1; python_version >= '3.5' --hash=sha256:bc2f976c0e918659f723401c4f834deb8a8e7798a71be4382e024bcc3f7e23a8 --hash=sha256:3a584b28086bc93c888a6c2aa5c92ed1ae20932f078c46509a66dce9ea5533f2 --hash=sha256:b3b9ad80f8b68519cc3372a6ca85ae02cc5a8807723ac366b53c0f089db19e4a --hash=sha256:db6db0f45d2c63ddb1a9d18d1b9b22f308e52c83638c26b422d520a815c4b3fb --hash=sha256:c52ce2883dc193824989a9b97a76ca86ecd1fa7955b14f87bf367a61b6232511 --hash=sha256:f379b7f83f23fe12823085cd6b906edc49df969eb99757f58ff382349a3303c6 --hash=sha256:ce584af5de8830d8701b8979b18fcf450cef9a382b1a3c8ef189bedc408faf1e --hash=sha256:9102b59e8337f9874638fcfc9ac3734a0cfadb100e47d55c20d0dc6087fb4692 --hash=sha256:9b930776c0ae0c691776f4d2891ebc5362af86f152dd0da463a6614074cb1b02 --hash=sha256:df89642981b94e7db5596818499c4b2219028f2a528c9c37cc1de45bf2fd3a3f --hash=sha256:f18d68f2be6bf0e89f1521af2b1bb46e66ab0018faafa81d70f358153170a317 --hash=sha256:48e918b05850fffb070a496d2b5f97fc31d15d94ca33d3d08a4f86e26d4e7c5d --hash=sha256:17668ec6722b1b7a3a05cc0167659f6c95b436d25a36c2d52db0eca7d3f72593 --hash=sha256:040b237f58ff7d800e6e0fd89c8439b841f777dd99b4a9cca04d6935564b9409 --hash=sha256:da456eeec17fa8aa4594d9a9f27c0b1060b6a75f2419fe0c00609587b2695f4a --hash=sha256:4439be27e4eee76c7632c2427ca5e73703151b22cae23e64adb243a9c2f565d8 --hash=sha256:c22c75b5f394f3d47105045ea551e08a3e804dc7e01b37800ca35b58f856c3d6! Will try again.
Installing initially failed dependencies...
[InstallError]:   File "c:\python37\lib\site-packages\pipenv\cli\command.py", line 253, in install
[InstallError]:       site_packages=state.site_packages
[InstallError]:   File "c:\python37\lib\site-packages\pipenv\core.py", line 2063, in do_install
[InstallError]:       keep_outdated=keep_outdated
[InstallError]:   File "c:\python37\lib\site-packages\pipenv\core.py", line 1312, in do_init
[InstallError]:       pypi_mirror=pypi_mirror,
[InstallError]:   File "c:\python37\lib\site-packages\pipenv\core.py", line 900, in do_install_dependencies
[InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[InstallError]:   File "c:\python37\lib\site-packages\pipenv\core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "c:\python37\lib\site-packages\pipenv\core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
[pipenv.exceptions.InstallError]:     "__main__", mod_spec)
[pipenv.exceptions.InstallError]:   File "c:\python37\lib\runpy.py", line 85, in _run_code
[pipenv.exceptions.InstallError]:     exec(code, run_globals)
[pipenv.exceptions.InstallError]:   File "C:\Users\Administrator\.virtualenvs\Modmail-zMg-DQ-A\Scripts\pip.exe\__main__.py", line 4, in <module>
[pipenv.exceptions.InstallError]: ModuleNotFoundError: No module named 'pip'
ERROR: Couldn't install package: aiohttp
 Package installation failed...
     ================================ 7/27 - 00:00:02
c:\python37\lib\subprocess.py:883: ResourceWarning: subprocess 14444 is still running
  ResourceWarning, source=self)
sys:1: ResourceWarning: unclosed file <_io.FileIO name=5 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=6 mode='rb' closefd=True>
c:\python37\lib\subprocess.py:883: ResourceWarning: subprocess 11752 is still running
  ResourceWarning, source=self)
sys:1: ResourceWarning: unclosed file <_io.FileIO name=7 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=8 mode='rb' closefd=True>
c:\python37\lib\subprocess.py:883: ResourceWarning: subprocess 12984 is still running
  ResourceWarning, source=self)
sys:1: ResourceWarning: unclosed file <_io.FileIO name=9 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=10 mode='rb' closefd=True>
c:\python37\lib\subprocess.py:883: ResourceWarning: subprocess 10200 is still running
  ResourceWarning, source=self)
sys:1: ResourceWarning: unclosed file <_io.FileIO name=11 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=12 mode='rb' closefd=True>
c:\python37\lib\subprocess.py:883: ResourceWarning: subprocess 13100 is still running
  ResourceWarning, source=self)
sys:1: ResourceWarning: unclosed file <_io.FileIO name=13 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=14 mode='rb' closefd=True>
c:\python37\lib\subprocess.py:883: ResourceWarning: subprocess 13900 is still running
  ResourceWarning, source=self)
sys:1: ResourceWarning: unclosed file <_io.FileIO name=15 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=16 mode='rb' closefd=True>

C:\Users\Administrator\Desktop\Modmail>
```

I tried reinstalling Python many times, Including downgrading to 3.7.8 but still got the same result. I also tried deleting my `Pipfile.lock` file but had another error so I abandoned doing that. 

I'd be happy to provide more information if asked.

**Comment by fourjr** [comment]
This is not a modmail issue, seems more like a pipenv issue. Seems like https://github.com/pypa/pipenv/pull/4262 and https://github.com/pypa/pipenv/issues/4220 are looking to fix this.
