### ISSUE TITLE
[BUG] Error raised when creating a new thread with `contact` command, or using react to contact.

### ISSUE THREAD

**Issue by Jerrie-Aries** [kyb3r/modmail#2970]
**Describe the bug**
Error raised when creating a new thread using `contact` command, or using react to contact. However the thread was successfully created.

**Bot Info**
Bot version: `3.8.5`
Host method: `Self-Host, Heroku`

**To Reproduce**
1. Who can reproduce (ex. anyone, owners)? -Anyone.
2. Where can it be reproduced (ex. in thread channels, recipient DM's)?
3. Done what to cause the error?- Open a new thread using `contact <user>` command, or react to contact.
4. Any recently made changes to your bot? - No.
5. Errored

**Error Logs**
```py
2021-03-11T00:05:37.164016+00:00 app[worker.1]: 03/11/21 00:05:37 core.clients[444] - DEBUG: Retrieving user 610629583628140559 logs.
2021-03-11T00:05:37.235820+00:00 app[worker.1]: 03/11/21 00:05:37 core.clients[519] - DEBUG: Created a log entry, key 5515a544a14b.
2021-03-11T00:05:37.398719+00:00 app[worker.1]: Task exception was never retrieved
2021-03-11T00:05:37.398722+00:00 app[worker.1]: future: <Task finished name='Task-34' coro=<Thread.setup() done, defined at /app/core/thread.py:106> exception=AttributeError("'NoneType' object has no attribute 'attachments'")>
2021-03-11T00:05:37.398722+00:00 app[worker.1]: Traceback (most recent call last):
2021-03-11T00:05:37.398723+00:00 app[worker.1]:   File "/app/core/thread.py", line 255, in setup
2021-03-11T00:05:37.398725+00:00 app[worker.1]:     await asyncio.gather(
2021-03-11T00:05:37.398725+00:00 app[worker.1]:   File "/app/core/thread.py", line 248, in activate_auto_triggers
2021-03-11T00:05:37.398726+00:00 app[worker.1]:     message = DummyMessage(copy.copy(initial_message))
2021-03-11T00:05:37.398726+00:00 app[worker.1]:   File "/app/core/models.py", line 230, in __init__
2021-03-11T00:05:37.398727+00:00 app[worker.1]:     message.attachments = []
2021-03-11T00:05:37.398727+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'attachments'
```

**Additional context**
Possible solution:
In `core/models.py` line 230:
https://github.com/kyb3r/modmail/blob/480ad57fb1e262595adc24c5b2aa23da8ff650fc/core/models.py#L229-L231

Replace with:
```py
if message is not None:
    message.attachments = []
```

That's what I tried. I'm not quite sure whether or not it would interfere with auto-triggers feature.

**Comment by Jerrie-Aries** [comment]
Fixed in 9d4813d25e9d0d6cc2ac70d14dd63ebac043aea6
