### ISSUE TITLE
[BUG]: Issue with custom plugin imports

### ISSUE THREAD

**Issue by Atharv-Agarwal** [kyb3r/modmail#3129]
### Bot Version

3.10.2

### How are you hosting Modmail?

Heroku

### Error Logs

https://hastebin.cc/idopokofux.apache

### Screenshots

![unknown](https://user-images.githubusercontent.com/49218334/144875641-6e25d742-b0e1-4dd3-9c2b-8622ea03396a.png)
You can see here all my plugins that are installed. 

### Additional Information

I have around 12 plugins installed which are stored in my repo here - (https://github.com/Atharv-Agarwal/cord). However each time I reboot/ Heroku restarts my bot, a random plugin does not install. An example of the error it throws is in the hastebin link. If I manually install it it works, until the next reboot when again a random plugin doesn't install automatically. 

PS: If I have a different repo for each plugin it works without issues, only when I put it all in the same repo do I have these issues. 

I have tried asking for help in the official support server but I wasn't able to fix my issue.

**Comment by fourjr** [comment]
Was there anything relevant in the error logs?

**Comment by Cordila** [comment]
Cant repro anymore since I am not hosting with heroku atm. Dont have this issue with vps hosting.

**Comment by Cordila** [comment]
```
ERROR: Error when loading plugin Atharv-Agarwal/plugins/snipe@main. Plugin removed from config.
Traceback (most recent call last):
  File "/app/cogs/plugins.py", line 158, in initial_load_plugins
    await self.load_plugin(plugin)
  File "/app/cogs/plugins.py", line 261, in load_plugin
    self.bot.load_extension(plugin.ext_string)
  File "/app/.heroku/python/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 674, in load_extension
    spec = importlib.util.find_spec(name)
  File "/app/.heroku/python/lib/python3.9/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'plugins.Atharv-Agarwal.plugins.snipe-main'
```
Found an old error

**Comment by fourjr** [comment]
Unable to reproduce in latest version
