### ISSUE TITLE
Modmail bot won't work correctly

### ISSUE THREAD

**Issue by SJuola** [kyb3r/modmail#32]
Hello, my Modmail bot doesn't seem to be working. When I send it a message, I won't get it in the mod mail channel. In the log history this shows up:

2018-03-18T23:08:23.263756+00:00 app[worker.1]: Ignoring exception in on_message
2018-03-18T23:08:23.263973+00:00 app[worker.1]: Traceback (most recent call last):
2018-03-18T23:08:23.264024+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 224, in _run_event
2018-03-18T23:08:23.264028+00:00 app[worker.1]:     yield from coro(*args, **kwargs)
2018-03-18T23:08:23.264075+00:00 app[worker.1]:   File "bot.py", line 379, in on_message
2018-03-18T23:08:23.264078+00:00 app[worker.1]:     await self.process_modmail(message)
2018-03-18T23:08:23.264117+00:00 app[worker.1]:   File "bot.py", line 353, in process_modmail
2018-03-18T23:08:23.264120+00:00 app[worker.1]:     blocked = top_chan.topic.split('Blocked\n-------')[1].strip().split('\n')
2018-03-18T23:08:23.264178+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'split'

Not sure what I did wrong, I gave the bot manage channel permissions.

**Comment by bananaboy21** [comment]
ez fix, you must have modified the topic of the channel or deleted the channel that the bot created
