### ISSUE TITLE
Bot not answering or sending messages

### ISSUE THREAD

**Issue by DeveloperTay** [kyb3r/modmail#40]
The bot isn't telling or showing me that someone has sent a message to the bot.

My logs on Heroku:2018-06-01T20:38:02.162854+00:00 app[worker.1]: Ignoring exception in on_message
2018-06-01T20:38:02.168891+00:00 app[worker.1]: Traceback (most recent call last):
2018-06-01T20:38:02.168906+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 224, in _run_event
2018-06-01T20:38:02.168908+00:00 app[worker.1]:     yield from coro(*args, **kwargs)
2018-06-01T20:38:02.169028+00:00 app[worker.1]:   File "bot.py", line 379, in on_message
2018-06-01T20:38:02.169031+00:00 app[worker.1]:     await self.process_modmail(message)
2018-06-01T20:38:02.169037+00:00 app[worker.1]:   File "bot.py", line 350, in process_modmail
2018-06-01T20:38:02.169040+00:00 app[worker.1]:     channel = discord.utils.get(guild.text_channels, topic=topic)
2018-06-01T20:38:02.169088+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'text_channels'
2018-06-01T20:40:15.790393+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=modmailbotv2.herokuapp.com request_id=f2f31472-175e-43d8-9d17-ebd44a2ad70f fwd="86.31.203.216" dyno= connect= service= status=503 bytes= protocol=https

**Comment by ExDe707** [comment]
Same issue here. Whenever someone PMs it, it reacts with a check emoji, but doesn't do anything further.

```Python
2018-07-29T16:51:08.080826+00:00 app[worker.1]: Ignoring exception in on_message
2018-07-29T16:51:08.091621+00:00 app[worker.1]: Traceback (most recent call last):
2018-07-29T16:51:08.092261+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 220, in _run_event
2018-07-29T16:51:08.092263+00:00 app[worker.1]:     await coro(*args, **kwargs)
2018-07-29T16:51:08.092398+00:00 app[worker.1]:   File "bot.py", line 379, in on_message
2018-07-29T16:51:08.092400+00:00 app[worker.1]:     await self.process_modmail(message)
2018-07-29T16:51:08.092750+00:00 app[worker.1]:   File "bot.py", line 350, in process_modmail
2018-07-29T16:51:08.092753+00:00 app[worker.1]:     channel = discord.utils.get(guild.text_channels, topic=topic)
2018-07-29T16:51:08.092829+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'text_channels'
```

**Comment by ExDe707** [comment]
@fourjr

**Comment by mariete1801** [comment]
To me happens the same. The bot reacts to de PM, but ir does not do anything else

**Comment by kyb3r** [comment]
Fixed this
