### ISSUE TITLE
Bot not responding to PMs

### ISSUE THREAD

**Issue by ExDe707** [kyb3r/modmail#52]
I've set it up and gave it administrator permissions, double checked Client ID, Bot Token and Guild ID. It created a new channel, bot-info. Whenever someone PMs it, it reacts with a check emoji, but doesn't do anything further. It's supposed to make a new channel when someone PMs it but that's not the case. This is parsed everytime whenever someone PMs it.

```Python
2018-07-29T16:51:08.080826+00:00 app[worker.1]: Ignoring exception in on_message
2018-07-29T16:51:08.091621+00:00 app[worker.1]: Traceback (most recent call last):
2018-07-29T16:51:08.092261+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 220, in _run_event
2018-07-29T16:51:08.092263+00:00 app[worker.1]:     await coro(*args, **kwargs)
2018-07-29T16:51:08.092398+00:00 app[worker.1]:   File "bot.py", line 379, in on_message
2018-07-29T16:51:08.092400+00:00 app[worker.1]:     await self.process_modmail(message)
2018-07-29T16:51:08.092750+00:00 app[worker.1]:   File "bot.py", line 350, in process_modmail
2018-07-29T16:51:08.092753+00:00 app[worker.1]:     channel = discord.utils.get(guild.text_channels, topic=topic)
2018-07-29T16:51:08.092829+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'text_channels'
```

**Comment by Brunph** [comment]
same problem here

**Comment by ExDe707** [comment]
@fourjr @4rqm If I don't get a response I will drop this bot and move on to get a different one.

**Comment by fourjr** [comment]
if you want to, you can drop this bot. and, please look through other issues before opening more, #51

**Comment by ItsDiqmond** [comment]
Just switch to a new Modmail bot because this bot is bad and the owner of the bot isn't even answering.

**Comment by Cryptoix** [comment]
@ItsDiqmond What bot

**Comment by fourjr** [comment]
i agree

**Comment by ProLessSkill** [comment]
same. its not responding.

**Comment by kyb3r** [comment]
I fixed this issue, try deploying again.
