### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by GrenadeMaster11** [kyb3r/modmail#58]
2018-09-17T17:30:50.921828+00:00 app[worker.1]: 
2018-09-17T17:32:56.927937+00:00 app[worker.1]: Ignoring exception in on_message
2018-09-17T17:32:56.929175+00:00 app[worker.1]: Traceback (most recent call last):
2018-09-17T17:32:56.941384+00:00 app[worker.1]:     await coro(*args, **kwargs)
2018-09-17T17:32:56.941430+00:00 app[worker.1]:   File "bot.py", line 379, in on_message
2018-09-17T17:32:56.941376+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 221, in _run_event
2018-09-17T17:32:56.941432+00:00 app[worker.1]:     await self.process_modmail(message)
2018-09-17T17:32:56.941469+00:00 app[worker.1]:   File "bot.py", line 350, in process_modmail
2018-09-17T17:32:56.941474+00:00 app[worker.1]:     channel = discord.utils.get(guild.text_channels, topic=topic)
2018-09-17T17:32:56.941550+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'text_channels'

**Comment by kyb3r** [comment]
I fixed this issue, try deploying again.
