### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text_channels'

### ISSUE THREAD

**Issue by peter-russell** [kyb3r/modmail#61]
When a DM is sent to the bot, it emoji reacts with ✅, but the message isn't being displayed as a channel in the server. The bot-info channel is available, though. The following error(s) keep occurring in Heroku when a message is sent to the bot.

> 2018-11-02T11:08:38.395920+00:00 app[worker.1]: Ignoring exception in on_message
2018-11-02T11:08:38.396107+00:00 app[worker.1]: Traceback (most recent call last):
2018-11-02T11:08:38.396163+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 225, in _run_event
2018-11-02T11:08:38.396167+00:00 app[worker.1]:     await coro(*args, **kwargs)
2018-11-02T11:08:38.396173+00:00 app[worker.1]:   File "bot.py", line 382, in on_message
2018-11-02T11:08:38.396175+00:00 app[worker.1]:     await self.process_modmail(message)
2018-11-02T11:08:38.396179+00:00 app[worker.1]:   File "bot.py", line 353, in process_modmail
2018-11-02T11:08:38.396182+00:00 app[worker.1]:     channel = discord.utils.get(guild.text_channels, topic=topic)
2018-11-02T11:08:38.396239+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'text_channels'

**Comment by peter-russell** [comment]
@fourjr

**Comment by Celtics2034** [comment]
Have you figured out a solution for this? I am having the same issue. @peter-russell

**Comment by peter-russell** [comment]
No, still doesn't work. @Celtics2034

**Comment by peter-russell** [comment]
@4rqm

**Comment by csojinb** [comment]
So, I looked into this, the issue appears to be that the bot is not correctly picking up the GUILD_ID from the env variable. I haven't figured out why that is, but I have confirmed that deploying it with the GUILD_ID hardcoded [here](https://github.com/kyb3r/modmail/blob/master/bot.py#L25) seems to work just fine.

**Comment by kyb3r** [comment]
@csojinb this actually only happens if you added the bot to the server **after** you started it. This is because when the bot starts it checks the guilds that it currently is in, and finds the guild from the provided guild_id and stores it in `self.guild`. So if you start the bot before you added the stored attribute is set to None. I fixed this issue just now by making `self.guild` a property.
