### ISSUE TITLE
Bot responds with checkmark and doesn't create a thread

### ISSUE THREAD

**Issue by Celtics2034** [kyb3r/modmail#62]
I have the bot set up in my discord server but it doesn't create a thread when messaged it only responds with a checkmark emoji

**Comment by SgtSkillz** [comment]
Happens with me too.

**Comment by SamuelPlays** [comment]
Same!

**Comment by RobsPlayz** [comment]
Says: 2018-11-16T22:10:38.146800+00:00 app[worker.1]: Ignoring exception in on_message
2018-11-16T22:10:38.149995+00:00 app[worker.1]: Traceback (most recent call last):
2018-11-16T22:10:38.150105+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 225, in _run_event
2018-11-16T22:10:38.150107+00:00 app[worker.1]:     await coro(*args, **kwargs)
2018-11-16T22:10:38.150160+00:00 app[worker.1]:   File "bot.py", line 382, in on_message
2018-11-16T22:10:38.150162+00:00 app[worker.1]:     await self.process_modmail(message)
2018-11-16T22:10:38.150200+00:00 app[worker.1]:   File "bot.py", line 372, in process_modmail
2018-11-16T22:10:38.150202+00:00 app[worker.1]:     category=categ
2018-11-16T22:10:38.150239+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/guild.py", line 647, in create_text_channel
2018-11-16T22:10:38.150241+00:00 app[worker.1]:     data = await self._create_channel(name, overwrites, ChannelType.text, category, reason=reason)
2018-11-16T22:10:38.150291+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/http.py", line 213, in request
2018-11-16T22:10:38.150293+00:00 app[worker.1]:     raise HTTPException(r, data)
2018-11-16T22:10:38.150367+00:00 app[worker.1]: discord.errors.HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
2018-11-16T22:10:38.150369+00:00 app[worker.1]: In parent_id: Category does not exist

**Comment by kyb3r** [comment]
Did you type `<prefix>setup` @RobsPlayz

**Comment by SamuelPlays** [comment]
I did but it never works. I want to try it again so I'll let you know if it does work.

**Comment by kyb3r** [comment]
It seems like only people who added the bot to their servers after they deployed it got the issue. I pushed a change to the code that fixes this issue.
